---
title: "First Knit"
author: "Cesar Guillen"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
I attended East Side High School, where I barely graduated because I had a breakdown and did not turn in any assignments for a class that I needed for graduating. If I were to compare my English and Math class, I did better in my English classes than my Math classes. The subject I did the best in was Psychology, which inlfluenced why I chose Psychology as my major.   

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
The laptop I use at home is a Samsung laptop. On a scale of 1 to 10, I would rate my knowledge as a 6. And Since my brother is an online gamer our internet connection is very good.   
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
I would rather be called by my classmates as Cesar. I also still get called by my friends as Cesar because I don't really like nicknames like that.   
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
I want to achieve the title of a certified psychologist for young adults and children. My subject that I have the greatest interests in are mostly Psychology based. the degree that I am trying to obtain is in Psychology or in Child Psychology.   
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
The most common country that I visit almost every year is Mexico, and in the future I would like to visit different parts of the United Kingdom. And I have not joined the military, and the branch I would want to get drafted by would probably be the airforce.   
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
I had previously took Math 115 last semester, but due to low attendance of the whole class it was dropped. And I knew that this class is only general education requirement, and that for transforming that Math 116 would be a better option. The grade that I would like to work for and that would not upset my current plan would be a B or above.    
   
 






  




